name: encurtalinkapp
description: "projeto de desafio do nubank o projeto em si encutra link e exibe uma lista"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.8
  logging: 1.3.0
  provider: 6.1.2
  go_router: 14.6.2
  shared_preferences: ^2.3.5
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.2
flutter:
  uses-material-design: true